db = "/app/db"

relay {
    bind = "0.0.0.0"
    port = 7777

    name = "My Storage Relay"
    description = "Self-hosted Nostr relay"

    pubkey = ""

    maxEventSize = 131072
    maxContentLength = 65536
}