// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
config({ path: path.resolve(__dirname, "../../.env") });

// See src/prisma.ts for why this is derived rather than read directly.
// Unlike prisma.ts, the Prisma CLI's datasource.url must be a plain
// string, so user/password are URL-encoded here — arbitrary passwords may
// contain characters (`/`, `@`, `:`, etc.) that would otherwise corrupt it.
const databaseUrl =
  process.env["DATABASE_URL"] ??
  `postgresql://${encodeURIComponent(process.env["POSTGRES_USER"]!)}:${encodeURIComponent(process.env["POSTGRES_PASSWORD"]!)}@${process.env["POSTGRES_HOST"]}:${process.env["POSTGRES_PORT"]}/${process.env["POSTGRES_DB"]}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
